Emm/gam 14
encoreee/GameDevPractikum pull request #10
Opened 2023-04-26 18:47 UTC by OluwadahunsiA

Верстка Error Pages 404 и 500. 

![image](https://user-images.githubusercontent.com/70890589/234673353-7b012a83-7953-4b93-b42d-6aced4570481.png)

2023-04-26 19:40 UTC, encoreee approved these changes

2023-04-27 15:53 UTC, dmitrii-yp commented on packages/client/package.json
> +    "identity-obj-proxy": "^3.0.0",
А не в devDependencies эту штуку надо? Это же для джеста. И версию можно зафиксировать.

2023-04-27 15:56 UTC, dmitrii-yp commented on packages/client/src/features/errors/Error.tsx
> +        <Typography sx={styles.subtext}>{errorMessage}</Typography>
Сообщение с текстом ошибки не отображается на 404.

2023-04-27 15:59 UTC, dmitrii-yp commented on packages/client/src/infrastructure/api/auth/authApi.ts
> +  singin = (singinRequest: SinginRequest) => {
В gam14 только верстка страниц 400 и 500. Добавляя api реквесты мы пересечемся, потому что я делаю логику авторизации.

2023-04-27 16:00 UTC, dmitrii-yp requested changes
Написал несколько комментов.

2023-04-27 17:18 UTC, OluwadahunsiA commented on packages/client/package.json
> +    "identity-obj-proxy": "^3.0.0",
Я зафиксил. Вообще не установил зависимости. Это из за того что я брал последные изменения.

2023-04-27 17:19 UTC, OluwadahunsiA commented on packages/client/src/features/errors/Error.tsx
> +        <Typography sx={styles.subtext}>{errorMessage}</Typography>
починил

2023-04-27 17:22 UTC, OluwadahunsiA commented on packages/client/src/infrastructure/api/auth/authApi.ts
> +  singin = (singinRequest: SinginRequest) => {
Я брал обновления из ветки gam-20 посколко там уже обновили настройки проекта. Может поэтиому у меня api реквесты

2023-04-27 17:23 UTC, OluwadahunsiA commented
> Написал несколько комментов.

Исправил

2023-04-27 19:52 UTC, dmitrii-yp approved these changes

2023-04-28 13:36 UTC, merged