Alexraykov2000/gam 21
encoreee/GameDevPractikum pull request #14
Opened 2023-04-29 20:49 UTC by encoreee

Вёрстка экрана игры Начало: например, обратный отсчёт, лоадер, экран с подсказками о том, как играть или просто кнопка «Старт».

![image](https://user-images.githubusercontent.com/44232406/235323643-130faf0c-d22b-4d0c-87ff-5d6ca5dbe4dd.png)

2023-05-01 14:58 UTC, rakuraev requested changes
Это пулреквест в мэин ветку, поменяй плз!

2023-05-03 06:54 UTC, kirei-io approved these changes

2023-05-03 07:09 UTC, dmitrii-yp commented on packages/client/src/features/gameStart/GameStartPage.tsx
> +      clearInterval(timerIn);
Не нужно ли тут очищать и timerOut, если пользователь перейдет на другую страницу, когда этот таймер еще не будет сброшен в timerIn

2023-05-03 07:14 UTC, dmitrii-yp commented on packages/client/src/features/gameStart/GameStartPage.tsx
> +      setChecked(() => false);
Не коммента, а вопрос. Почему тут функция возвращающая false, а не просто false?

2023-05-03 07:22 UTC, dmitrii-yp commented on packages/client/src/features/gameStart/GameStartPage.tsx
> +  useEffect(() => {
Разделял на 2 отдельных useEffect, чтобы легче было понять происходящее или еще зачем то нужно так делать?

2023-05-03 17:38 UTC, encoreee commented on packages/client/src/features/gameStart/GameStartPage.tsx
> +      clearInterval(timerIn);
Он очищается внутри первого выполнения таймера, кажется больше нигде не нужно очищать?

2023-05-03 17:41 UTC, encoreee commented on packages/client/src/features/gameStart/GameStartPage.tsx
> +      setChecked(() => false);
Стрелочная функция гарантирует (это неточно) что в стейт попадет прямо сейчас, ведь метод доступа в стейт асинхронный...

2023-05-03 17:42 UTC, encoreee commented on packages/client/src/features/gameStart/GameStartPage.tsx
> +  useEffect(() => {
Да, по тематике

2023-05-05 07:05 UTC, merged