Rakuraev/gam 17
encoreee/GameDevPractikum pull request #15
Opened 2023-05-01 15:20 UTC by rakuraev

## GAM-17 Верстка страниц форума

Что сделано: 
- Сверстаны страницы форума и треда
![CleanShot 2023-05-01 at 18 11 41](https://user-images.githubusercontent.com/52157662/235474564-939fcdd8-85f3-4b52-ab44-f37002a0f719.png)
![CleanShot 2023-05-01 at 18 12 34](https://user-images.githubusercontent.com/52157662/235474720-57a83523-2292-424d-9d64-8dc7acb1d8a7.png)
- Пагинация для списка тредов
![CleanShot 2023-05-01 at 18 13 57](https://user-images.githubusercontent.com/52157662/235474954-8823dc79-8140-4bc0-886c-104ba9acbe33.gif)
- Создание новой темы(треда)
![CleanShot 2023-05-01 at 18 15 35](https://user-images.githubusercontent.com/52157662/235475469-7157d9c2-8121-4679-9100-cf68a5a11f97.gif)

2023-05-02 07:13 UTC, encoreee reviewed
Крутая работа!

2023-05-02 07:13 UTC, encoreee commented on packages/client/src/features/forum/components/Message.tsx
> +          {`If you're looking for a game that will transport you back to the
Тут вроде бы нет интерполяции?

2023-05-02 07:13 UTC, encoreee commented on packages/client/src/features/forum/components/Message.tsx
> +      <Grid item xs={8}>
xs в сумме должно быть 12. А вообще то мы, у нас вся разметка не адаптивная

2023-05-02 07:13 UTC, encoreee commented on packages/client/src/features/forum/components/Message.tsx
> +const smallText = { fontSize: '0.5rem', color: '#fff' };
*Style

2023-05-02 07:13 UTC, encoreee commented on packages/client/src/features/forum/pages/ThreadList.tsx
> +// Это нормально или все-таки внести в отдельный файл?
Мне ревьюер советов отдельный

2023-05-02 07:13 UTC, encoreee commented on packages/client/src/shared/helpers/date/formatDate.ts
> +  date = 'dd.LL.yyyy', // '12.12.2023'
LL?

2023-05-02 18:08 UTC, rakuraev commented on packages/client/src/components/ModalWindow.tsx
> +export const useModal = (title: ReactNode): ModalProps => {
Мне кажется, что в app( предпологаю, что в app конфигурируется что-то глобальное) не самая лучшая идея, потому что мы там конфигруриуем store, возможно, там появится что-то еще и не совсем понятно, почему хук для использования компонента должен лежать там.

У меня вот 2 варианта как это выстраивать.

1.  Отдельная директория компонента и связанные с этим компонентом сущности(hooks,consts,test etc.)    
            
   - ModalWindow (Директория)
     - ModalWindow.tsx (Компонент)
     - ModalWindow.spec.ts (Тесты)
     - useModalWindow(Hook)
     - types.d.ts
     - const,utils etc.
     - index.ts (Public Api для экспорта)
 
 Все в одно месте, а экспорты настраиваем в index.ts через  `publicApi`.
 
 2. Либо все в отдельные директории, например shared/hooks, shared/utils, shared/что-то еще
 
 Что думаешь? Может вынести это на обсуждение?

2023-05-02 18:38 UTC, encoreee commented on packages/client/src/shared/helpers/date/formatDate.ts
> +  date = 'dd.LL.yyyy', // '12.12.2023'
Так а работает? 
![image](https://user-images.githubusercontent.com/44232406/235755786-95b2c127-0ccf-4739-a6cb-0230290d08ac.png)

Первый столбец если применяется в одиночестве, а если при форматировании то второй?

2023-05-02 19:08 UTC, rakuraev commented on packages/client/src/shared/helpers/date/formatDate.ts
> +  date = 'dd.LL.yyyy', // '12.12.2023'
Ненене, там я так понял формат токены, я так понял как-то слова склоняют на разных языках.
![CleanShot 2023-05-02 at 22 06 17](https://user-images.githubusercontent.com/52157662/235762212-90146f47-325f-4a43-bb44-0efb28d47bdc.png)

2023-05-02 20:04 UTC, rakuraev commented on packages/client/src/app/forum/types.d.ts
> +  threadList: StateStatus;
Вообще, я закладывал идею, что значение в state и state.status имеет одинаковое название и так понятно, к какому состоянию статус относится просто если у меня добавятся еще переменные, как мне различать статусы?

2023-05-03 16:02 UTC, dmitrii-yp commented on packages/client/src/features/forum/pages/ThreadList.tsx
> +            <Button
Для кнопок Next page, New thread можно добавить подчеркивание, чтобы понятно было что кнопка активна.

2023-05-03 16:05 UTC, dmitrii-yp commented on packages/client/src/features/forum/components/Message.tsx
> +      </Grid>
Предлагаю под сообщением добавить еще дату и время и кнопку reply.

2023-05-03 16:07 UTC, dmitrii-yp commented on packages/client/src/features/forum/pages/Thread.tsx
> +          <Button variant="text" sx={cleanButtonStyles}>
Может лучше не показывать кнопки если нет страниц?

2023-05-04 21:59 UTC, rakuraev commented on packages/client/src/features/forum/pages/Thread.tsx
> +          <Button variant="text" sx={cleanButtonStyles}>
Там пока просто верстка и нет никакой логики, думаю что можно это в следущих тасках сделать.

2023-05-04 21:59 UTC, rakuraev commented on packages/client/src/features/forum/components/Message.tsx
> +      </Grid>
Добавил

2023-05-04 22:00 UTC, rakuraev commented on packages/client/src/features/forum/pages/ThreadList.tsx
> +            <Button
![CleanShot 2023-05-05 at 00 57 54](https://user-images.githubusercontent.com/52157662/236338902-1481af06-1efb-42b1-bd82-7bfa101c5eb1.gif)(Переключаюсь на TAB)
MUI компоненты подсвечивают кнопки при фокусе

2023-05-04 22:02 UTC, rakuraev commented on packages/client/src/features/forum/components/NewThreadModal.tsx
> +          value={themeName}
проп `autoFocus` не работает почему-то с react.strictMode(Типа 2 раза маунтится, а фокус на первом срабатывает), сделал через `ref`

2023-05-05 07:07 UTC, encoreee approved these changes

2023-05-05 07:24 UTC, kirei-io approved these changes

2023-05-05 07:48 UTC, DazzlingFame commented
Привет, ПР получился очень большим. Лучше дробить реквесты и задачи, если понимаешь, что в них будет больше 500-800 строк изменений. В этот раз я посмотрю изменения, но времени это займёт больше, чем обычно

<img width="145" alt="image" src="https://user-images.githubusercontent.com/15292833/236403335-fafa2213-289f-4e3f-bcca-c0facf419a3b.png">

2023-05-05 11:09 UTC, DazzlingFame requested changes
Привет, крутая работа. Отписался в комментариях по коду

2023-05-05 11:09 UTC, DazzlingFame commented on packages/client/src/components/DataField.tsx
> +    return (
Тут есть 2 варианта, как это поправить
1. Вынести 2 компонента для `LABEL_LEFT` и для `LABEL_TOP` и в зависимости от условия отдавать нужный компонент
2. Сделать единый return, где вариант отдавать в условии
```
return (
  {variant === DATA_FIELD_VARIANTS.LABEL_LEFT ? (<верстка для left>) : (<верстка для top>)}
)
```

2023-05-05 11:09 UTC, DazzlingFame commented on packages/client/src/components/DataField.tsx
> +            {props.label}{' '}
лишний `{' '}`

Посмотри сразу по всему диффу на такое

2023-05-05 11:09 UTC, DazzlingFame commented on packages/client/src/features/forum/components/Message.tsx
> +          <Stack direction={'row'} alignItems={'center'} gap={'0.5rem'}>
Если это мок сообщения, то стоит сразу добавить в `Message` тип пропсов, сделать логику проброса пропсов в нужные компоненты, а снаружи уже, в месте использования `Message` закинуть мокнутый объект с пропсами (его хорошо было бы ещё вынести в константу)

2023-05-05 11:09 UTC, DazzlingFame commented on packages/client/src/features/forum/components/TBThreads.tsx
> +  } else if (threadListStatus === STATE_STATUSES.IDLE) {
У тебя тут прямо явное разделение на компоненты просматривается. Заведи лучше для каждого ифа свой компонент и получится:
- место, где лежит логика выбора что отрисовать не забивается самим кодом компонентов
- для каждого стейта есть свой отделенный компонент, который легко изменять

2023-05-05 11:09 UTC, DazzlingFame commented on packages/client/src/features/forum/pages/ThreadList.tsx
> +  const threadsPerPage = 9;
Эта константа никак не зависит от компонента => её можно вынести наружу

+ нейминг хардкодных констант традиционно выглядит так `const THREADS_PER_PAGE = 9;`

2023-05-05 11:09 UTC, DazzlingFame commented on packages/client/src/features/forum/pages/ThreadList.tsx
> +  });
Этот эффект без второго параметра с deps будет вызыватся на каждый ререндер. Это целевое состояние?

2023-05-05 11:09 UTC, DazzlingFame commented on packages/client/src/features/forum/pages/ThreadList.tsx
> +              }}
А в чем тут необходимость дестракчеринга (...{})?

2023-05-05 11:29 UTC, DazzlingFame commented
Не забудь ещё в пачку написать сообщение с запросом на ревью в правильном формате (это запрос от кураторов курса)

2023-05-07 14:54 UTC, rakuraev commented on packages/client/src/components/ModalWindow/useModalWindow.ts
> +  return { open, handleClose, handleOpen, title };
Мне показалось, что такая реализация более лаконична.
```ts
const modalProps = useModalWindow('title')
return <ModalWindow {...ModalWindowProps} />
```
vs

```ts
const modalProps:ModalProps = {...useModalWindow(), title:'title'}
return <ModalWindow {...ModalWindowProps} />
```
К тому же, возможно, будущем понадобиться менять `title` и тогда мне будет достаточно просто расширить hook 1-им методом, нежели писать эту логику в компоненте или же как-то менять hook,с условием что пришел 'title` или нет.

2023-05-08 19:47 UTC, rakuraev commented on packages/client/src/features/forum/pages/ThreadList.tsx
> +  });
Поправил

2023-05-08 19:47 UTC, rakuraev commented on packages/client/src/features/forum/pages/ThreadList.tsx
> +              }}
Поправил

2023-05-08 19:57 UTC, rakuraev commented on packages/client/src/infrastructure/api/forum/__data.ts
> +const __forumThreads: ForumThreadList = [
Поправил

2023-05-08 19:57 UTC, rakuraev commented on packages/client/src/features/forum/types.d.ts
> +};
Поправил

2023-05-08 19:58 UTC, rakuraev commented on packages/client/src/components/DataField.tsx
> +  ...props
Поправил

2023-05-08 19:58 UTC, rakuraev commented on packages/client/src/components/DataField.tsx
> +    return (
Поправил

2023-05-08 19:59 UTC, rakuraev commented on packages/client/src/components/DataField.tsx
> +            {props.label}{' '}
Поправил

2023-05-08 19:59 UTC, rakuraev commented on packages/client/src/features/forum/components/Message.tsx
> +          <Stack direction={'row'} alignItems={'center'} gap={'0.5rem'}>
Добавил

2023-05-08 20:04 UTC, rakuraev commented on packages/client/src/features/forum/components/TBThreads.tsx
> +  } else if (threadListStatus === STATE_STATUSES.IDLE) {
Я вот разделил, но оставил эти компоненты в одном файле. Такое допустимо, или все-таки лучше "один компонент -  один файл"?

2023-05-08 20:13 UTC, rakuraev commented on packages/client/src/app/forum/forumSlice.ts
> +      console.log(state);
Я что-то забыл про это, поправлю

2023-05-09 20:28 UTC, DazzlingFame commented on packages/client/src/app/forum/forumSlice.ts
> +import { ForumApi } from '@/infrastructure/api/forum/ForumApi';
А зачем тут этот игнор?

2023-05-09 20:28 UTC, DazzlingFame commented on packages/client/src/app/forum/forumSlice.ts
> +console.log(threadMessagesAdapter.getInitialState());
Если ты не хочешь, чтобы юзеры видели этот лог, лучше его убрать :)

2023-05-09 20:29 UTC, DazzlingFame commented on packages/client/src/app/forum/types.ts
> +// export type
Кажется ты забыл тут убрать коммент

2023-05-09 20:34 UTC, DazzlingFame commented on packages/client/src/infrastructure/api/forum/ForumApi.ts
> +  return new Promise((res) => getData(res, 'FORUM_TREADS_MOCK'));
а зачем этот игнор?

2023-05-09 20:34 UTC, DazzlingFame commented on packages/client/src/infrastructure/api/forum/ForumApi.ts
> +};
а зачем этот игнор?

2023-05-09 20:35 UTC, DazzlingFame commented on packages/client/src/features/forum/components/TBThreads.tsx
> +  } else if (threadListStatus === STATE_STATUSES.IDLE) {
Можно оставить в одном

2023-05-09 20:36 UTC, DazzlingFame commented
Привет, зарезолвил поправленное, оставил немного новых вопросов

2023-05-10 07:57 UTC, rakuraev commented on packages/client/src/app/forum/forumSlice.ts
> +import { ForumApi } from '@/infrastructure/api/forum/ForumApi';
Забыл убрать, поправил.

2023-05-10 07:59 UTC, rakuraev commented on packages/client/src/infrastructure/api/forum/ForumApi.ts
> +};
Поправил

2023-05-10 08:52 UTC, DazzlingFame approved these changes
👍

2023-05-10 12:02 UTC, merged