Alexraykov2000/gam 27
encoreee/GameDevPractikum pull request #23
Opened 2023-05-16 10:06 UTC by encoreee

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-05-16 11:38 UTC, rakuraev approved these changes

2023-05-16 12:48 UTC, kirei-io approved these changes
Проделана очень большая качественная работа. Реализованны основные игровые механики.

![image](https://github.com/encoreee/GameDevPractikum/assets/44925378/14d7b579-c02c-4efc-a3bd-51b14fe5d178)

Нашел баг, что при смене сцены остаются снаряды, по хорошему бы очищать сцену от объектов перед переходом на дргую.

2023-05-16 13:28 UTC, encoreee commented on packages/client/src/features/game/GalagaGame.ts
> +    SceneManager.setCurrentSceneByIndex(1);
Как раз хотел сказать что это не так что бы и нужно

2023-05-16 14:07 UTC, encoreee commented on packages/client/src/features/game/game-object/components/OrdinaryEnemyObjectPhysics.ts
> +    if (this.actionNumber === 0) {
ok

2023-05-16 18:23 UTC, encoreee commented on packages/client/src/features/game/GalagaGame.ts
> +    SceneManager.setCurrentSceneByIndex(1);
Снаряды тоже нельзя теперь выпускать до окончания таймаута

2023-05-16 18:23 UTC, encoreee commented on packages/client/src/features/game/game-object/GameObject.ts
> +    public currentAngle: number,
радианы

2023-05-16 19:14 UTC, encoreee commented on packages/client/src/features/game/game-object/components/OrdinaryEnemyObjectPhysics.ts
> +        const vy = Math.sin(gameObject.currentAngle) * gameObject.radius;
ok

2023-05-16 19:14 UTC, encoreee commented on packages/client/src/features/game/game-object/components/WarriorEnemyObjectPhysics.ts
> +        const vy = Math.sin(gameObject.currentAngle) * gameObject.radius;
ok

2023-05-16 19:15 UTC, encoreee commented on packages/client/src/features/game/game-object/components/WarriorEnemyObjectPhysics.ts
> +          new Vector2(400, 100).multiply(dt)
Пока не понял как это обозначить и использовать, может позже придет что то стоящее в голову

2023-05-17 16:34 UTC, dmitrii-yp commented
Работа офигенная и по объему и по качеству. Уже даже подзалип и поиграл, со спрайтами вообще супер. Теперь пытаюсь разобраться как у нас тут все работает)

2023-05-17 16:35 UTC, dmitrii-yp commented on packages/client/src/features/gameStart/GameStartPage.tsx
> +    }, 1500);
Я бы еще уменьшил, до 1000 и 500 соответсвенно. Можно сделать переменные TIME_IN и TIME_OUT, чтобы не было магических значений в коде.

2023-05-18 07:17 UTC, encoreee commented on packages/client/src/features/gameStart/GameStartPage.tsx
> +    }, 1500);
ok

2023-05-20 13:27 UTC, DazzlingFame requested changes
Привет, просмотрел код, отписал комментарии.

Обрати особое внимание на реализацию наследования повторяющихся в `GameSceneХ` методов от какого-то родительского класса `GameScene`.

2023-05-20 13:27 UTC, DazzlingFame commented on packages/client/src/features/game/game-object/components/Graphics/PlayerInput.ts
> +  public canShut: boolean;
`canShoot`?

2023-05-20 13:27 UTC, DazzlingFame commented on packages/client/src/features/game/game-object/components/Physics/OrdinaryEnemyObjectPhysics.ts
> +      case 0:
Комменты по всему update:

- Хочется либо вместо `actionNumber` видеть какой-то `enum` экшнов, либо иметь где-то на виду доку с описанием какой намбер что делает. Целевое состояние - понимать, что в каком кейсе обрабатывается, увидев `update` без необходимости куда-то лезть в другие файлы
- Все захардкоженные цифры, например как тут - `new Vector2(-400, 100).multiply(dt)` стоит вынести в файл с константами/конфиг и тут уже использовать эти константы. Тут сейчас вижу штуку, которая называется "Magic numbers", те числа без какого-либо нейминга или описания

2023-05-20 13:27 UTC, DazzlingFame commented on packages/client/src/features/game/game-object/components/Physics/WarriorEnemyObjectPhysics.ts
> +    switch (this.actionNumber) {
Аналогично тому, что выше:

Комменты по всему update:

- Хочется либо вместо actionNumber видеть какой-то enum экшнов, либо иметь где-то на виду доку с описанием какой намбер что делает. Целевое состояние - понимать, что в каком кейсе обрабатывается, увидев update без необходимости куда-то лезть в другие файлы
- Все захардкоженные цифры, например как тут - new Vector2(-400, 100).multiply(dt) стоит вынести в файл с константами/конфиг и тут уже использовать эти константы. Тут сейчас вижу штуку, которая называется "Magic numbers", те числа без какого-либо нейминга или описания

2023-05-20 13:27 UTC, DazzlingFame commented on packages/client/src/features/game/scenes/GameSceneLevel1.ts
> +        if (this.enemyMetrics.currentRow === squadRow) {
Код ниже выглядит сильно повторяющимся. В параметрах createEnemy, например, отличается толко 5 параметр

Попробуй переписать, оставив общие части вне условий, а в if завернуть только отличающиеся куски

2023-05-20 13:27 UTC, DazzlingFame commented on packages/client/src/features/game/scenes/GameSceneLevel2.ts
> +  public tryCreateEnemy(index: number) {
А `tryCreateEnemy` отличается в разных `GameScene`? Если он везде одинаковый, то стоит вынести его в родительский класс и таким образом не придется каждый раз его переопределять. Аналогично для всех одинаковых методов внутри `GameSceneХ`

2023-05-20 13:27 UTC, DazzlingFame requested changes
Привет, просмотрел код, отписал комментарии.

Обрати особое внимание на реализацию наследования повторяющихся в `GameSceneХ` методов от какого-то родительского класса `GameScene`.

2023-05-22 07:50 UTC, encoreee commented on packages/client/src/features/game/game-object/components/Graphics/PlayerInput.ts
> +  public canShut: boolean;
Поправил

2023-05-22 07:50 UTC, encoreee commented on packages/client/src/features/game/core/Collider.ts
> +    }
Откомментировал

2023-05-22 07:51 UTC, encoreee commented on packages/client/src/features/game/Config.ts
>  export const canvasSize: Size = {
Немного изменил нэйминг

2023-05-22 07:51 UTC, encoreee commented on packages/client/src/features/game/game-object/components/Physics/OrdinaryEnemyObjectPhysics.ts
> +      case 0:
Откомментировала, привел описание работы метода

2023-05-22 07:51 UTC, encoreee commented on packages/client/src/features/game/game-object/components/Physics/WarriorEnemyObjectPhysics.ts
> +    switch (this.actionNumber) {
Откомментировал, привел описание работы метода

2023-05-22 07:52 UTC, encoreee commented on packages/client/src/features/game/scenes/GameSceneLevel1.ts
> +        if (this.enemyMetrics.currentRow === squadRow) {
Выделил повторяющуюся часть , провел рефакторинг

2023-05-22 12:00 UTC, DazzlingFame reviewed
Привет, круто, что получилось зарефакторить и избавиться от повторений кода. Отдельный плюс за комментарии в коде 👍 . 

Оставил ещё несколько правок в коде

2023-05-22 12:00 UTC, DazzlingFame commented on packages/client/src/features/game/game-object/components/Objects/Player.ts
> +  public setShutAbility(ability: boolean) {
```suggestion
  public setShootAbility(ability: boolean) {
```

2023-05-22 12:00 UTC, DazzlingFame commented on packages/client/src/features/game/game-object/components/Physics/OrdinaryEnemyObjectPhysics.ts
> +        if (gameObject.currentAngle > 0) {
Сильно понятнее не стало, на самом деле из-за того, что в разных кейсах повторяются комментарии, стало даже чуть хуже понятно
```
      // Оработка линейного движения
      case 0:
```

```
      case 2:
        // Оработка линейного движения
```

2023-05-22 12:00 UTC, DazzlingFame commented on packages/client/src/features/game/game-object/components/Physics/OrdinaryEnemyObjectPhysics.ts
> +        if (gameObject.currentAngle > 0) {
Чем 0 отличается от 2? Хочется в комментариях видеть именно то, что заставило тебя вынеси этот код в отдельный кейс

2023-05-22 12:00 UTC, DazzlingFame commented on packages/client/src/features/game/scenes/SceneManager.ts
> +    }
А зачем тут `switch case`? насколько я вижу, код повторяется и нужно обработать только `Not implemented` `nextScene`

2023-05-22 12:00 UTC, DazzlingFame commented on packages/client/src/features/game/scenes/SceneUtils/SceneUtils.ts
> +    new Vector2(10, 40),
А что такое `10, 40`? Если у этого есть физ смысл, то это нужно вынести в конфиг

2023-05-22 12:00 UTC, DazzlingFame commented on packages/client/src/features/game/scenes/SceneUtils/SceneUtils.ts
> +        { width: 60, height: 60 },
Аналогичный комментарий про физ смысл `60, 60` и конфиг

2023-05-23 07:45 UTC, encoreee commented on packages/client/src/features/game/scenes/SceneUtils/SceneUtils.ts
> +        { width: 60, height: 60 },
Постарался везде вынести в конфиги

2023-05-23 07:45 UTC, encoreee commented on packages/client/src/features/game/scenes/SceneUtils/SceneUtils.ts
> +    new Vector2(10, 40),
Постарался везде вынести в конфиги

2023-05-23 07:46 UTC, encoreee commented on packages/client/src/features/game/game-object/components/Physics/OrdinaryEnemyObjectPhysics.ts
> +        if (gameObject.currentAngle > 0) {
Полностью переделал.

2023-05-23 07:47 UTC, encoreee commented on packages/client/src/features/game/game-object/components/Objects/Player.ts
> +  public setShutAbility(ability: boolean) {
ок

2023-05-23 07:56 UTC, DazzlingFame approved these changes
Привет, получилось круто, аппрув!

2023-05-23 08:00 UTC, merged